spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20

  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix:

# JWT验证
jwt:
  header: Authorization
  secret: senthink1112!
  prefix: "Bearer "
  expiration: 86400

uri:
  auth:
    login: "/api/v1/auth/login"
    register: "/api/v1/auth/register"
    refresh: "/api/v1/auth/refresh"

# server 端口
server:
  port: 9000

# 时间相关的配置
date:
  # 系统使用的时区(包括Jackson)
  timezone: "GMT+8"

# LOG配置
logging:
  level:
    com.senthink.gl: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

